### ISSUE TITLE
data_eng in per unit

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#257] opened 2020-04-08 04:08 UTC
@pseudocubic what is your main use case for being able to convert the engineering data model to per unit as well? 

Since many fields are contained in data objects which are shared by many components (potentially at different voltage levels), this it not so trivial. At least I do not see a clearly best/unique way to define a conversion, so perhaps your use case could help with that.

**Comment by pseudocubic** [comment] 2020-04-08 14:05
My biggest use case for this is that when working with optimization cases it is more natural to have voltage magnitudes in the per-unit representation, and having that in the engineering model would be very valuable, since by design the engineering model will be more straightforward to understand. Related, it will make visualization easier, because often we will want to represent the deviation of the voltage from nominal.

**Comment by pseudocubic** [comment] 2020-04-15 22:19
Resolved by offline conversion: only jump variables can be return in per-unit in the engineering model, for the purposes of easier debugging for optimization users

**Closed by pseudocubic** 2020-04-15 22:19 UTC
Labels: models
